# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       kei ka-hei cheung
email:       kei.khcheung@gmail.com
tagline:     'kei ka-hei cheung' # A short description used as part of the title tag of the home page like 'title | tagline'.
description: 'Portfolio & personal blog of Kei Ka-hei Cheung. Experience Deisnger based in Cologne, Germany. Design projects of digital services & products. A few thoughts on interactions, audiovisuals, writing, current issues, and plants. Occasionally some projects for fun such as short film production, photography, graphics, and drawings.'
author:      'Kei Ka-hei Cheung'
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://keikhcheung.com/' # The base hostname & protocol for your site
twitter:
  username:  keikhcheung
  card:      summary
github:      https://github.com/keikhcheung
linkedin:    https://www.linkedin.com/in/kei-cheung/
facebook:    ''

markdown:  kramdown
permalink: pretty
paginate:  10

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-seo-tag

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext