# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: kei ka-hei cheung
realname:  Kei Ka-hei Cheung
email: kei.khcheung@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio of Kei Ka-hei Cheung.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://keikhcheung.com" # the base hostname & protocol for your site
twitter_username: keikhcheung
github_username:  keikhcheung
linkedin_username: kei-cheung
dribbble_username: keikhcheung
repo: https://github.com/keikhcheung/keikhcheung.github.io/

# Project URL
# permalink:   /work/:title/

# Build settings
markdown: kramdown
