# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: kei ka-hei cheung
realname:  Kei Ka-hei Cheung
email: kei.khcheung@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio of Kei Ka-hei Cheung, Information Architect based in Cologne, Germany. Showcase for chiefly Experience Design projects for digital services and the Internet of things; as well as product design, short film production, photography, graphics, and drawings.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://keikhcheung.com" # the base hostname & protocol for your site
author: keikhcheung
twitter:
  username: keikhcheung
  card: summary
facebook:
  publisher: https://www.facebook.com/kei.khcheung
social:
  name: Kei Ka-hei Cheung
  links:
    - https://twitter.com/keikhcheung
    - https://www.linkedin.com/in/kei-cheung/
    - https://www.facebook.com/kei.khcheung
    - https://github.com/keikhcheung
    - https://dribbble.com/keikhcheung
lang: en_GB

twitter_username: keikhcheung
github_username:  keikhcheung
linkedin_username: kei-cheung
dribbble_username: keikhcheung
repo: https://github.com/keikhcheung/keikhcheung.github.io/

# Project URL
# permalink:   /work/:title/

# Build settings
markdown: kramdown

#load blog
collections:
  blog

plugins:
  - jekyll-seo-tag